source 'https://github.com/CocoaPods/Specs'
source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'UnityFramework' do
  pod 'UnityAds', '~> 4.16.3'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
